version: '3'

services:
  app:
    command: node src/index.js
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      MYSQL_HOST: ${MYSQL_HOST:-mysql}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      OJS_API_URL: ${OJS_API_URL}
      OJS_API_KEY: ${OJS_API_KEY}

  mysql:
    image: mysql:8.0
    volumes:
      - glpc-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      default:
        aliases:
          - ${MYSQL_HOST:-mysql}
      
volumes:
  glpc-mysql-data:
  
