version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OJS_BASE_URI: ${OJS_BASE_URI}
        OJS_SECTION_IDS: ${OJS_SECTION_IDS}
        BLOCK_CLASS_NAME: ${BLOCK_CLASS_NAME:-block_inline_html_related}
        BLOCK_CLASS_TARGET: ${BLOCK_CLASS_TARGET:-block_inline_html_published_date}
        BLOCK_TITLE: ${BLOCK_TITLE:-Cross References}
        DEBUG_MODE: ${DEBUG_MODE:-false}
    ports:
      - "${EXPOSED_PORT:-8080}:3000"
    working_dir: /app
    environment:
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      MYSQL_HOST: ${MYSQL_HOST:-mysql}
      MYSQL_USER: ${MYSQL_USER:-relateduser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB:-relateddb}
      OJS_PROTOCOL_AND_DNS: ${OJS_PROTOCOL_AND_DNS}
      OJS_BASE_URI: ${OJS_BASE_URI}
      OJS_API_KEY: ${OJS_API_KEY}
      OJS_SECTION_IDS: ${OJS_SECTION_IDS}
      BLOCK_CLASS_NAME: ${BLOCK_CLASS_NAME:-block_inline_html_related}
      BLOCK_CLASS_TARGET: ${BLOCK_CLASS_TARGET:-block_inline_html_published_date}
      BLOCK_TITLE: ${BLOCK_TITLE:-Cross References}
      ALLOW_BROKEN_SSL: ${ALLOW_BROKEN_SSL:-false}
    restart: always

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB:-relateddb}
      MYSQL_USER: ${MYSQL_USER:-relateduser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      default:
        aliases:
          - ${MYSQL_HOST:-mysql}
    restart: always
      
volumes:
  mysql-data:
  
