version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OJS_BASE_URI: ${OJS_BASE_URI}
    ports:
      - "${EXPOSED_PORT:-8080}:3000"
    working_dir: /app
    environment:
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      MYSQL_HOST: ${MYSQL_HOST:-mysql}
      MYSQL_USER: ${MYSQL_USER:-relateduser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB:-relateddb}
      OJS_PROTOCOL_AND_DNS: ${OJS_PROTOCOL_AND_DNS}
      OJS_BASE_URI: ${OJS_BASE_URI}
      OJS_API_KEY: ${OJS_API_KEY}
      OJS_SECTION_IDS: ${OJS_SECTION_IDS}

  mysql:
    image: mysql:8.0
    volumes:
      - glpc-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB:-relateddb}
      MYSQL_USER: ${MYSQL_USER:-relateduser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      default:
        aliases:
          - ${MYSQL_HOST:-mysql}
      
volumes:
  glpc-mysql-data:
  
